name: advent-of-code-2023
channels:
  - conda-forge
dependencies:
  - _r-mutex=1.0.1
  - appnope=0.1.3
  - asttokens=2.4.1
  - bwidget=1.9.14
  - bzip2=1.0.8
  - c-ares=1.23.0
  - ca-certificates=2023.11.17
  - cairo=1.18.0
  - cctools_osx-64=973.0.1
  - clang=16.0.6
  - clang-16=16.0.6
  - clang_impl_osx-64=16.0.6
  - clang_osx-64=16.0.6
  - clangxx=16.0.6
  - clangxx_impl_osx-64=16.0.6
  - clangxx_osx-64=16.0.6
  - comm=0.1.4
  - compiler-rt=16.0.6
  - compiler-rt_osx-64=16.0.6
  - curl=8.4.0
  - dart-sass=1.58.3
  - debugpy=1.8.0
  - decorator=5.1.1
  - deno=1.28.2
  - deno-dom=0.1.35
  - esbuild=0.19.2
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - expat=2.5.0
  - font-ttf-dejavu-sans-mono=2.37
  - font-ttf-inconsolata=3.000
  - font-ttf-source-code-pro=2.038
  - font-ttf-ubuntu=0.83
  - fontconfig=2.14.2
  - fonts-conda-ecosystem=1
  - fonts-conda-forge=1
  - freetype=2.12.1
  - fribidi=1.0.10
  - gettext=0.21.1
  - gfortran_impl_osx-64=12.3.0
  - gfortran_osx-64=12.3.0
  - gmp=6.3.0
  - graphite2=1.3.13
  - gsl=2.7
  - harfbuzz=8.3.0
  - icu=73.2
  - importlib-metadata=6.8.0
  - importlib_metadata=6.8.0
  - ipykernel=6.26.0
  - ipython=8.18.1
  - isl=0.25
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=5.5.0
  - krb5=1.21.2
  - ld64_osx-64=609
  - lerc=4.0.0
  - libblas=3.9.0
  - libcblas=3.9.0
  - libclang-cpp16=16.0.6
  - libcurl=8.4.0
  - libcxx=16.0.6
  - libdeflate=1.19
  - libedit=3.1.20191231
  - libev=4.33
  - libexpat=2.5.0
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran-devel_osx-64=12.3.0
  - libgfortran5=13.2.0
  - libglib=2.78.1
  - libiconv=1.17
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libllvm16=16.0.6
  - libnghttp2=1.58.0
  - libopenblas=0.3.25
  - libpng=1.6.39
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libssh2=1.11.0
  - libtiff=4.6.0
  - libwebp-base=1.3.2
  - libxml2=2.11.6
  - libzlib=1.2.13
  - llvm-openmp=17.0.6
  - llvm-tools=16.0.6
  - make=4.3
  - matplotlib-inline=0.1.6
  - mpc=1.3.1
  - mpfr=4.2.1
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - openssl=3.2.0
  - packaging=23.2
  - pandoc=3.1.1
  - pango=1.50.14
  - parso=0.8.3
  - pcre2=10.42
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.1
  - pixman=0.42.2
  - platformdirs=4.0.0
  - prompt-toolkit=3.0.41
  - psutil=5.9.5
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.9.18
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=25.1.1
  - quarto=1.3.450
  - r-askpass=1.2.0
  - r-base=4.2.3
  - r-base64enc=0.1_3
  - r-bslib=0.6.1
  - r-cachem=1.0.8
  - r-cli=3.6.1
  - r-curl=5.1.0
  - r-digest=0.6.33
  - r-ellipsis=0.3.2
  - r-evaluate=0.23
  - r-fastmap=1.1.1
  - r-fontawesome=0.5.2
  - r-fs=1.6.3
  - r-glue=1.6.2
  - r-here=1.0.1
  - r-highr=0.10
  - r-htmltools=0.5.7
  - r-jquerylib=0.1.4
  - r-jsonlite=1.8.7
  - r-knitr=1.45
  - r-later=1.3.1
  - r-lattice=0.22_5
  - r-lifecycle=1.0.4
  - r-magrittr=2.0.3
  - r-matrix=1.6_4
  - r-memoise=2.0.1
  - r-mime=0.12
  - r-openssl=2.1.1
  - r-packrat=0.9.2
  - r-png=0.1_8
  - r-processx=3.8.2
  - r-ps=1.7.5
  - r-quarto=1.3
  - r-r6=2.5.1
  - r-rappdirs=0.3.3
  - r-rcpp=1.0.11
  - r-rcpptoml=0.2.2
  - r-renv=1.0.3
  - r-reticulate=1.34.0
  - r-rlang=1.1.2
  - r-rmarkdown=2.25
  - r-rprojroot=2.0.4
  - r-rsconnect=1.1.1
  - r-rstudioapi=0.15.0
  - r-sass=0.4.7
  - r-stringi=1.8.2
  - r-stringr=1.5.1
  - r-sys=3.4.2
  - r-tinytex=0.49
  - r-vctrs=0.6.4
  - r-withr=2.5.2
  - r-xfun=0.41
  - r-yaml=2.3.7
  - readline=8.2
  - setuptools=68.2.2
  - sigtool=0.1.3
  - six=1.16.0
  - stack_data=0.6.2
  - tapi=1100.0.11
  - tk=8.6.13
  - tktable=2.10
  - tornado=6.3.3
  - traitlets=5.14.0
  - typing_extensions=4.8.0
  - tzdata=2023c
  - wcwidth=0.2.12
  - wheel=0.42.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - zlib=1.2.13
  - zstd=1.5.5
